# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///javadb
      username: root
      password: shao778851
      driver-class-name: com.mysql.cj.jdbc.Driver
